/*
Copyright 2023 nineinfra.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/nineinfra/nineinfra/api/v1alpha1"
	scheme "github.com/nineinfra/nineinfra/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NineClustersGetter has a method to return a NineClusterInterface.
// A group's client should implement this interface.
type NineClustersGetter interface {
	NineClusters(namespace string) NineClusterInterface
}

// NineClusterInterface has methods to work with NineCluster resources.
type NineClusterInterface interface {
	Create(ctx context.Context, nineCluster *v1alpha1.NineCluster, opts v1.CreateOptions) (*v1alpha1.NineCluster, error)
	Update(ctx context.Context, nineCluster *v1alpha1.NineCluster, opts v1.UpdateOptions) (*v1alpha1.NineCluster, error)
	UpdateStatus(ctx context.Context, nineCluster *v1alpha1.NineCluster, opts v1.UpdateOptions) (*v1alpha1.NineCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NineCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NineClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NineCluster, err error)
	NineClusterExpansion
}

// nineClusters implements NineClusterInterface
type nineClusters struct {
	client rest.Interface
	ns     string
}

// newNineClusters returns a NineClusters
func newNineClusters(c *NineinfraV1alpha1Client, namespace string) *nineClusters {
	return &nineClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nineCluster, and returns the corresponding nineCluster object, and an error if there is any.
func (c *nineClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NineCluster, err error) {
	result = &v1alpha1.NineCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nineclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NineClusters that match those selectors.
func (c *nineClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NineClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NineClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nineclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nineClusters.
func (c *nineClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nineclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nineCluster and creates it.  Returns the server's representation of the nineCluster, and an error, if there is any.
func (c *nineClusters) Create(ctx context.Context, nineCluster *v1alpha1.NineCluster, opts v1.CreateOptions) (result *v1alpha1.NineCluster, err error) {
	result = &v1alpha1.NineCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nineclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nineCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nineCluster and updates it. Returns the server's representation of the nineCluster, and an error, if there is any.
func (c *nineClusters) Update(ctx context.Context, nineCluster *v1alpha1.NineCluster, opts v1.UpdateOptions) (result *v1alpha1.NineCluster, err error) {
	result = &v1alpha1.NineCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nineclusters").
		Name(nineCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nineCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nineClusters) UpdateStatus(ctx context.Context, nineCluster *v1alpha1.NineCluster, opts v1.UpdateOptions) (result *v1alpha1.NineCluster, err error) {
	result = &v1alpha1.NineCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nineclusters").
		Name(nineCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nineCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nineCluster and deletes it. Returns an error if one occurs.
func (c *nineClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nineclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nineClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nineclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nineCluster.
func (c *nineClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NineCluster, err error) {
	result = &v1alpha1.NineCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nineclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
